baseURL = 'https://200word.org/'
languageCode = 'en-us'
title = '200 words'
theme = 'minimal'

[params]
  description = "200 words a day"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
